services:
  nginx:
    image: nginx:alpine
    container_name: my-nginx
    ports:
      - "${APP_PORT:-8082}:80"
    volumes:
      - type: bind
        source: ./html        # на хосте
        target: /usr/share/nginx/html  # в контейнере
        read_only: true

      - type: bind
        source: ./nginx/conf.d        # на хосте
        target: /etc/nginx/conf.d  # в контейнере
        read_only: true
        
    deploy:
      resources:
        limits:
          cpus: "1.0"        # максимум 1 CPU
          memory: 256M       # максимум 256 мегабайт

    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: unless-stopped
